spring.application.name=observability-actuator
server.port=8090

#ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3.5:9b
spring.ai.ollama.chat.options.temperature=0.1