spring.application.name=flight-booking

#ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3-vl:8b

logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor= debug